---
title: Overtuigende presentatie van gegevens
hero_image: images/banner.png
description: Maak een datavisualisatie voor een onderwerp waar je gepassioneerd over bent
meta_title: Python-coderingsprojecten voor kinderen en tieners | Overtuigende gegevens
meta_description: Leer Python met de codeerprojecten van de Raspberry Pi Foundation voor kinderen en tieners. Maak een datavisualisatie in Python voor een onderwerp waar je gepassioneerd over bent.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - title: Wat ga je maken
  - title: Jouw idee
  - title: Bouw en test - Teken of grafiek
    completion:
      - engaged
  - title: Uitbreiden en testen - Gebruikersinteractie
    completion:
      - internal
  - title: Checklist
    completion:
      - external
  - title: Verbeter je project
  - title: Delen
  - title: Wat kun je verder nog doen?
