---
title: Persuasive data presentation
hero_image: images/banner.png
description: Create a data visualisation for a topic that you are passionate about
meta_title: Python coding projects for kids and teens | Persuasive data
meta_description: Learn Python with the Raspberry Pi Foundation's coding projects for kids and teens. Create a data visualisation in Python for a topic that you are passionate about.
version: 4
listed: true
copyedit: true
last_tested: '2021-03-26'
steps:
  - title: You will make
  - title: Your idea
  - title: Build and test - Draw or chart
    completion:
      - engaged
  - title: Expand and test - User interaction
    completion:
      - internal
  - title: Checklist
    completion:
      - external
  - title: Upgrade your project
  - title: Share
  - title: What next?
