title: Persuasive data presentation
hero_image: images/banner.png
description: Create a data visualisation for a topic that you are passionate about
version: 4
listed: false
copyedit: false
last_tested: "2021-03-26"
steps:
  - title: Introduction
  - title: Your idea
  - title: Build and test - Draw or chart
    completion: engaged
  - title: Expand and test - User interaction
  - title: Share
    completion: internal
  - title: Reflect
  - title: Upgrade your project
    completion: external 
  - title: What next?
